apiVersion: v1
kind: Secret
metadata:
  name: rsky-labeler-secrets
  namespace: atproto
type: Opaque
stringData:
  MOD_SERVICE_DID: "${MOD_SERVICE_DID}"
  MOD_SERVICE_EMAIL: "${MOD_SERVICE_EMAIL}"
  MOD_SERVICE_PASSWORD: "${MOD_SERVICE_PASSWORD}"
