apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: relay-know-me-tools-tls
  namespace: atproto
spec:
  secretName: relay-know-me-tools-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - relay.know-me.tools
