apiVersion: v1
kind: Service
metadata:
  name: rsky-relay
  namespace: atproto
  labels:
    app: rsky-relay
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: rsky-relay
