apiVersion: v1
kind: ConfigMap
metadata:
  name: rsky-feedgen-config
  namespace: atproto
data:
  FEEDGEN_SERVICE_DID: "did:web:feed.know-me.tools"
  FEEDGEN_HOSTNAME: "feed.know-me.tools"
  SHOW_SPONSORED_POST: "0"
  TRENDING_PERCENTILE: "0.9"
  ROCKET_PORT: "3000"
  ROCKET_ADDRESS: "0.0.0.0"
