apiVersion: v1
kind: Secret
metadata:
  name: rsky-feedgen-secrets
  namespace: atproto
type: Opaque
stringData:
  DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/rsky_feedgen"
  READ_REPLICA_URL_1: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/rsky_feedgen"
  READ_REPLICA_URL_2: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/rsky_feedgen"
  RSKY_API_KEY: "${RSKY_API_KEY}"
