apiVersion: v1
kind: Service
metadata:
  name: rsky-feedgen
  namespace: atproto
  labels:
    app: rsky-feedgen
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: rsky-feedgen
