apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: atproto-ssd-immediate
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
