apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: appview-know-me-tools-tls
  namespace: atproto
spec:
  secretName: appview-know-me-tools-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - appview.know-me.tools
