pub mod follow;

use crate::app::bsky::actor::{ProfileView, ProfileViewBasic};
use crate::app::bsky::richtext::Facet;
use crate::com::atproto::label::Label;
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ListViewBasic {
    pub uri: String,
    pub cid: String,
    pub name: String,
    pub purpose: ListPurpose,
    pub avatar: Option<String>,
    pub list_item_count: Option<usize>,
    pub labels: Option<Vec<Label>>,
    pub viewer: Option<ListViewerState>,
    pub indexed_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(tag = "$type")]
#[serde(rename = "app.bsky.graph.defs#listView")]
#[serde(rename_all = "camelCase")]
pub struct ListView {
    pub uri: String,
    pub cid: String,
    pub creator: ProfileView,
    pub name: String,
    pub purpose: ListPurpose,
    pub description: Option<String>,
    pub description_facets: Option<Vec<Facet>>,
    pub avatar: Option<String>,
    pub list_item_count: Option<usize>,
    pub labels: Option<Vec<Label>>,
    pub viewer: Option<ListViewerState>,
    pub indexed_at: String,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(tag = "$type")]
#[serde(rename = "app.bsky.graph.defs#starterPackViewBasic")]
#[serde(rename_all = "camelCase")]
pub struct StarterPackViewBasic {
    pub uri: String,
    pub cid: String,
    pub record: Value,
    pub creator: ProfileViewBasic,
    pub list_item_count: Option<usize>,
    pub joined_week_count: Option<usize>,
    pub joined_all_time_count: Option<usize>,
    pub labels: Option<Vec<Label>>,
    pub indexed_at: String,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub enum ListPurpose {
    /// A list of actors to apply an aggregate moderation action (mute/block) on.
    #[serde(rename = "app.bsky.graph.defs#modlist")]
    ModList,
    /// A list of actors used for curation purposes such as list feeds or interaction gating.
    #[serde(rename = "app.bsky.graph.defs#curatelist")]
    CurateList,
    /// A list of actors used for only for reference purposes such as within a starter pack.
    #[serde(rename = "app.bsky.graph.defs#referencelist")]
    ReferenceList,
    /// A list of feeds generated by the actor.
    #[serde(rename = "app.bsky.graph.defs#feedlist")]
    FeedList,
    /// A list of actors the actor might want to follow.
    #[serde(rename = "app.bsky.graph.defs#potentials")]
    Potentials,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct ListViewerState {
    pub muted: Option<bool>,
    pub blocked: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Relationship {
    pub did: String,
    pub display_name: Option<String>,
    pub handle: String,
    pub avatar: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub associated: Option<bool>,
    pub followed_by: Option<bool>,
    pub following: Option<bool>,
    pub followed_by_count: Option<usize>,
    pub following_count: Option<usize>,
    pub posts_count: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub indexed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub viewer: Option<RelationshipViewerState>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<Label>>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RelationshipViewerState {
    pub muted: Option<bool>,
    pub muted_by_list: Option<ListViewBasic>,
    pub following: Option<String>,
    pub followed_by: Option<String>,
    pub bsky_app_state: Option<BskyAppState>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BskyAppState {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pinned_post: Option<String>,
}
