apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: social-know-me-tools-tls
  namespace: atproto
spec:
  secretName: social-know-me-tools-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - social.know-me.tools
