apiVersion: v1
kind: ConfigMap
metadata:
  name: web-client-config
  namespace: atproto
data:
  NEXT_PUBLIC_ATP_SERVICE_URL: "https://pds.know-me.tools"
  NEXT_PUBLIC_ATP_APPVIEW_URL: "https://appview.know-me.tools"
  NEXTAUTH_URL: "https://social.know-me.tools"
