apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: atproto
  labels:
    app: web-client
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: web-client
