[package]
name = "rsky-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
# external
bstr = "1"
bus = "2"
color-eyre = "0.6"
derive_more = { version = "2", features = ["full"] }
hashbrown = "0.15"
http = "1"
httparse = "1.10"
magnetic = "2"
nix = { version = "0.29", features = ["event", "socket"] }
rtrb = "0.3"
rustls = "0.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
signal-hook = { version = "0.3", features = ["extended-siginfo"] }
thingbuf = "0.1"
thiserror = "2"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tungstenite = { version = "0.26", features = ["rustls-tls-native-roots"] }
url = "2"
