apiVersion: v1
kind: Secret
metadata:
  name: rsky-pds-secrets
  namespace: atproto
type: Opaque
stringData:
  PDS_ADMIN_PASS: "${PDS_ADMIN_PASS}"
  PDS_JWT_KEY_K256_PRIVATE_KEY_HEX: "${PDS_JWT_KEY_K256_PRIVATE_KEY_HEX}"
  PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: "${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}"
  PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX: "${PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX}"
  PDS_MAILGUN_API_KEY: "${PDS_MAILGUN_API_KEY}"
  PDS_MAILGUN_DOMAIN: "${PDS_MAILGUN_DOMAIN}"
  DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/rsky"
  AWS_ACCESS_KEY_ID: "${GCS_HMAC_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${GCS_HMAC_SECRET_KEY}"
  AWS_BUCKET: "${GCS_BUCKET_NAME}"
